apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-tech-challenge
  labels:
    app: fiap-tech-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiap-tech-challenge
  template:
    metadata:
      labels:
        app: fiap-tech-challenge
    spec:
      containers:
        - name: c-fiap-tech-challenge
          image: viniciuslvsrv/fiap-tech-challenge:v3
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "1m"   
              memory: "128Mi"
