apiVersion: v1
kind: Service
metadata:
  labels:
    app: fiap-tech-challenge-svc
  name: fiap-tech-challenge-loadbalancer-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: fiap-tech-challenge
  type: LoadBalancer