apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-tech-challenge
  labels:
    app: fiap-tech-challenge
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fiap-tech-challenge
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 
      maxSurge: 1        
  template:
    metadata:
      labels:
        app: fiap-tech-challenge
    spec:
      containers:
        - name: c-fiap-tech-challenge
          image: viniciuslvsrv/fiap-tech-challenge:v5
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "30m"
              memory: "499Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"