name: "Application K8S Pipeline"

on:
  push:
    branches:
      - main

env:
  REGION_DEFAULT: us-east-1

jobs:
  deploy:
    name: Deploying Kubernetes Resources
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.REGION_DEFAULT }}

      - name: Configure Kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ env.REGION_DEFAULT }} --name eks-tech-challenge

      - name: Deploy Kubernetes Manifests
        run: |
          kubectl apply -f ./k8s/deployment/deployment.yml
          kubectl apply -f ./k8s/svc/service.yml
          kubectl apply -f ./k8s/hpa.yml
          kubectl apply -f ./k8s/metrics.yml